# site settings
title: Ziggurat
subtitle: by Vladislav Nedelchev
email: nvlad@vt.edu
description: <br /> and released under the Creative Commons.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 2

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/andrewbanchich
  LinkedIn: https://www.linkedin.com/in/andrew-banchich-a4ba1195

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
